/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './singlepoll.component.ngfactory';
import * as import2 from './singlepoll.component';
import * as import3 from '../newpolls/poll.service';
import * as import4 from '@angular/common';
import * as import5 from './allmypolls.component';
import * as import6 from '@angular/router';
const styles_AllmypollsComponent:any[] = ['.contain[_ngcontent-%COMP%] {\n      background-color:  #f8f8f8;\n      padding: 20px 10px 20px 10px;\n      border-radius: 5px;\n\n    }\n    h1[_ngcontent-%COMP%], h3[_ngcontent-%COMP%] {\n      text-align: center;\n    }'];
export const RenderType_AllmypollsComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_AllmypollsComponent,
  data: {}
}
);
function View_AllmypollsComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-singlepoll',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.onClic(v.context.$implicit)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },import1.View_SinglePoll_0,import1.RenderType_SinglePoll)),
      import0.ɵdid(49152,(null as any),0,import2.SinglePoll,[import3.PollService],{poll: [
        0,
        'poll'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  },(null as any));
}
export function View_AllmypollsComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'contain'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Polls that you have created.'])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'Click a poll to edit or see results. ',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n\n  '])),
    (l()(),import0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_AllmypollsComponent_1)),
    import0.ɵdid(802816,(null as any),0,import4.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import5.AllmypollsComponent = v.component;
    const currVal_1:any = co.polls;
    ck(v,9,0,currVal_1);
  },(ck,v) => {
    var co:import5.AllmypollsComponent = v.component;
    const currVal_0:any = ((co.poll == null)? (null as any): co.poll.title);
    ck(v,6,0,currVal_0);
  });
}
function View_AllmypollsComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-allmypolls',([] as any[]),(null as any),(null as any),(null as any),View_AllmypollsComponent_0,RenderType_AllmypollsComponent)),
    import0.ɵdid(114688,(null as any),0,import5.AllmypollsComponent,[
      import3.PollService,
      import6.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AllmypollsComponentNgFactory:import0.ComponentFactory<import5.AllmypollsComponent> = import0.ɵccf('app-allmypolls',import5.AllmypollsComponent,View_AllmypollsComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvYWxsbXlwb2xscy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvYWxsbXlwb2xscy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9uZ3Roby9Eb2N1bWVudHMvSmF2YVNjcmlwdC9Wb3RpbmdfYXBwL2Fzc2V0cy9hcHAvbXlwb2xscy9hbGxteXBvbGxzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvYWxsbXlwb2xscy5jb21wb25lbnQudHMuQWxsbXlwb2xsc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9J2NvbnRhaW4nPlxyXG4gIDxoMT5Qb2xscyB0aGF0IHlvdSBoYXZlIGNyZWF0ZWQuPC9oMT5cclxuICA8aDM+Q2xpY2sgYSBwb2xsIHRvIGVkaXQgb3Igc2VlIHJlc3VsdHMuIHt7cG9sbD8udGl0bGV9fTwvaDM+XHJcblxyXG4gIDxhcHAtc2luZ2xlcG9sbFxyXG4gIFtwb2xsXT0ncG9sbCdcclxuICAqbmdGb3I9XCJsZXQgcG9sbCBvZiBwb2xsc1wiXHJcbiAgKGNsaWNrKT1cIm9uQ2xpYyhwb2xsKVwiPlxyXG4gIDwvYXBwLXNpbmdsZXBvbGw+XHJcbjwvZGl2PlxyXG4iLCI8YXBwLWFsbG15cG9sbHM+PC9hcHAtYWxsbXlwb2xscz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNJRTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUdBO1FBQUE7UUFBQTtNQUFBO01BSEE7SUFBQTtrQkFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBR3VCOzs7SUFGdkI7SUFEQSxTQUNBLFNBREE7Ozs7O01BSkY7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFxQjtJQUNuQjtJQUFJO0lBQWlDO0lBQ3JDO0lBQUk7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUF5RDtJQUU3RDtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUlpQjtJQUNiOzs7O0lBSEo7SUFGQSxTQUVBLFNBRkE7OztJQUZJO0lBQUE7Ozs7O0lDRk47Z0JBQUE7OztJQUFBO0tBQUE7OztJQUFBOzs7In0=
