/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.chart-container[_ngcontent-%COMP%] {\r\n  height: 500px;\r\n  width: 650px;\r\n}\r\n.poll-container[_ngcontent-%COMP%] {\r\n  padding: 20px;\r\n  background-color: #eee;\r\n  margin: 0px;\r\n}\r\n.options[_ngcontent-%COMP%] {\r\n  font-size: 1.3em;\r\n  margin-left: 0px;\r\n  padding-left: 0px;\r\n}\r\n\r\nbutton[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n  margin: 10px;\r\n}\r\n\r\n.submit[_ngcontent-%COMP%] {\r\n  background-color: #42ab9e;\r\n  border-color: #42ab9e;\r\n\r\n}\r\n\r\nselect[_ngcontent-%COMP%] {\r\n  width: 100%;\r\n  margin: 4px;\r\n}\r\n\r\n.dropdown[_ngcontent-%COMP%] {\r\n  margin-left: 0px;\r\n  padding-left: 0px;\r\n}\r\n\r\nchart[_ngcontent-%COMP%] {\r\n  height: 430px;\r\n  width: 430px;\r\n  margin: 0 auto;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvbXlwb2xscy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL25ndGhvL0RvY3VtZW50cy9KYXZhU2NyaXB0L1ZvdGluZ19hcHAvYXNzZXRzL2FwcC9teXBvbGxzL215cG9sbHMuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
