/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './singlepoll.component';
import * as import2 from '../newpolls/poll.service';
const styles_SinglePoll:any[] = ['.well[_ngcontent-%COMP%] {\n      background-color:  white;\n    }\n    .titular[_ngcontent-%COMP%] {\n      text-align: center;\n      font-size: 1.25em;\n      color: #42ab9e;\n    }\n    .titular[_ngcontent-%COMP%]:hover {\n      cursor: pointer;\n      background-color: #e7e7e7;\n    }'];
export const RenderType_SinglePoll:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_SinglePoll,
  data: {}
}
);
export function View_SinglePoll_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'titular well'
      ]
      ],(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.SinglePoll = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.onClick()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '\n',
      '\n'
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.SinglePoll = v.component;
    const currVal_0:any = co.poll.title;
    ck(v,1,0,currVal_0);
  });
}
function View_SinglePoll_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-singlepoll',([] as any[]),(null as any),(null as any),(null as any),View_SinglePoll_0,RenderType_SinglePoll)),
    import0.ɵdid(49152,(null as any),0,import1.SinglePoll,[import2.PollService],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SinglePollNgFactory:import0.ComponentFactory<import1.SinglePoll> = import0.ɵccf('app-singlepoll',import1.SinglePoll,View_SinglePoll_Host_0,{poll: 'poll'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvc2luZ2xlcG9sbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvc2luZ2xlcG9sbC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9uZ3Roby9Eb2N1bWVudHMvSmF2YVNjcmlwdC9Wb3RpbmdfYXBwL2Fzc2V0cy9hcHAvbXlwb2xscy9zaW5nbGVwb2xsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL215cG9sbHMvc2luZ2xlcG9sbC5jb21wb25lbnQudHMuU2luZ2xlUG9sbF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJ0aXR1bGFyIHdlbGxcIlxyXG4oY2xpY2spPVwib25DbGljaygpXCI+XHJcbnt7cG9sbC50aXRsZX19XHJcbjwvZGl2PlxyXG4iLCI8YXBwLXNpbmdsZXBvbGw+PC9hcHAtc2luZ2xlcG9sbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0FBO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFDQTtRQUFBO1FBQUE7TUFBQTtNQURBO0lBQUE7SUFDb0I7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUVkOzs7O0lBRmM7SUFBQTs7Ozs7SUNEcEI7Z0JBQUE7Ozs7In0=
