/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/forms';
import * as import3 from '@angular/http';
import * as import4 from '@angular/common';
import * as import5 from '@angular/router';
import * as import6 from '@angular/platform-browser';
import * as import7 from './app-routing.module';
import * as import8 from 'angular2-chartjs/dist/chart.module';
import * as import9 from './header/twitter.service';
import * as import10 from './newpolls/poll.service';
import * as import11 from './newpolls/newpolls.component.ngfactory';
import * as import12 from './mypolls/mypolls.component.ngfactory';
import * as import13 from './app.component.ngfactory';
import * as import14 from './newpolls/newpolls.component';
import * as import15 from './mypolls/mypolls.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _ɵba_0:import2.ɵba;
  _FormsModule_1:import2.FormsModule;
  _ReactiveFormsModule_2:import2.ReactiveFormsModule;
  _HttpModule_3:import3.HttpModule;
  _CommonModule_4:import4.CommonModule;
  _ErrorHandler_5:any;
  _NgProbeToken_6:any[];
  _ɵg_7:import5.ɵg;
  _APP_INITIALIZER_8:any[];
  _ApplicationInitStatus_9:import0.ApplicationInitStatus;
  _ɵf_10:import0.ɵf;
  _ApplicationRef_11:any;
  _ApplicationModule_12:import0.ApplicationModule;
  _BrowserModule_13:import6.BrowserModule;
  _ɵa_14:any;
  _UrlSerializer_15:import5.DefaultUrlSerializer;
  _RouterOutletMap_16:import5.RouterOutletMap;
  _ROUTER_CONFIGURATION_17:any;
  _LocationStrategy_18:any;
  _Location_19:import4.Location;
  _Compiler_20:import0.Compiler;
  _NgModuleFactoryLoader_21:import0.SystemJsNgModuleLoader;
  _ROUTES_22:any[];
  _Router_23:any;
  _RouterModule_24:import5.RouterModule;
  _AppRoutingModule_25:import7.AppRoutingModule;
  _ChartModule_26:import8.ChartModule;
  _AppModule_27:import1.AppModule;
  __ɵi_28:import2.ɵi;
  __FormBuilder_29:import2.FormBuilder;
  __BrowserXhr_30:import3.BrowserXhr;
  __ResponseOptions_31:import3.BaseResponseOptions;
  __XSRFStrategy_32:any;
  __XHRBackend_33:import3.XHRBackend;
  __RequestOptions_34:import3.BaseRequestOptions;
  __Http_35:any;
  __LOCALE_ID_36:any;
  __NgLocalization_37:import4.NgLocaleLocalization;
  __APP_ID_38:any;
  __IterableDiffers_39:any;
  __KeyValueDiffers_40:any;
  __DomSanitizer_41:import6.ɵe;
  __Sanitizer_42:any;
  __HAMMER_GESTURE_CONFIG_43:import6.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_44:any[];
  __EventManager_45:import6.EventManager;
  __ɵDomSharedStylesHost_46:import6.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_47:import6.ɵDomRendererFactory2;
  __RendererFactory2_48:any;
  __ɵSharedStylesHost_49:any;
  __Testability_50:import0.Testability;
  __Meta_51:import6.Meta;
  __Title_52:import6.Title;
  __ActivatedRoute_53:any;
  __NoPreloading_54:import5.NoPreloading;
  __PreloadingStrategy_55:any;
  __RouterPreloader_56:import5.RouterPreloader;
  __PreloadAllModules_57:import5.PreloadAllModules;
  __ROUTER_INITIALIZER_58:any;
  __APP_BOOTSTRAP_LISTENER_59:any[];
  __TwitterService_60:import9.TwitterService;
  __PollService_61:import10.PollService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import11.NewpollsComponentNgFactory,
      import12.MypollsComponentNgFactory,
      import13.AppComponentNgFactory
    ]
    ,[import13.AppComponentNgFactory]);
  }
  get _ɵi_28():import2.ɵi {
    if ((this.__ɵi_28 == null)) { (this.__ɵi_28 = new import2.ɵi()); }
    return this.__ɵi_28;
  }
  get _FormBuilder_29():import2.FormBuilder {
    if ((this.__FormBuilder_29 == null)) { (this.__FormBuilder_29 = new import2.FormBuilder()); }
    return this.__FormBuilder_29;
  }
  get _BrowserXhr_30():import3.BrowserXhr {
    if ((this.__BrowserXhr_30 == null)) { (this.__BrowserXhr_30 = new import3.BrowserXhr()); }
    return this.__BrowserXhr_30;
  }
  get _ResponseOptions_31():import3.BaseResponseOptions {
    if ((this.__ResponseOptions_31 == null)) { (this.__ResponseOptions_31 = new import3.BaseResponseOptions()); }
    return this.__ResponseOptions_31;
  }
  get _XSRFStrategy_32():any {
    if ((this.__XSRFStrategy_32 == null)) { (this.__XSRFStrategy_32 = import3.ɵb()); }
    return this.__XSRFStrategy_32;
  }
  get _XHRBackend_33():import3.XHRBackend {
    if ((this.__XHRBackend_33 == null)) { (this.__XHRBackend_33 = new import3.XHRBackend(this._BrowserXhr_30,this._ResponseOptions_31,this._XSRFStrategy_32)); }
    return this.__XHRBackend_33;
  }
  get _RequestOptions_34():import3.BaseRequestOptions {
    if ((this.__RequestOptions_34 == null)) { (this.__RequestOptions_34 = new import3.BaseRequestOptions()); }
    return this.__RequestOptions_34;
  }
  get _Http_35():any {
    if ((this.__Http_35 == null)) { (this.__Http_35 = import3.ɵc(this._XHRBackend_33,this._RequestOptions_34)); }
    return this.__Http_35;
  }
  get _LOCALE_ID_36():any {
    if ((this.__LOCALE_ID_36 == null)) { (this.__LOCALE_ID_36 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_36;
  }
  get _NgLocalization_37():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_37 == null)) { (this.__NgLocalization_37 = new import4.NgLocaleLocalization(this._LOCALE_ID_36)); }
    return this.__NgLocalization_37;
  }
  get _APP_ID_38():any {
    if ((this.__APP_ID_38 == null)) { (this.__APP_ID_38 = import0.ɵg()); }
    return this.__APP_ID_38;
  }
  get _IterableDiffers_39():any {
    if ((this.__IterableDiffers_39 == null)) { (this.__IterableDiffers_39 = import0.ɵl()); }
    return this.__IterableDiffers_39;
  }
  get _KeyValueDiffers_40():any {
    if ((this.__KeyValueDiffers_40 == null)) { (this.__KeyValueDiffers_40 = import0.ɵm()); }
    return this.__KeyValueDiffers_40;
  }
  get _DomSanitizer_41():import6.ɵe {
    if ((this.__DomSanitizer_41 == null)) { (this.__DomSanitizer_41 = new import6.ɵe(this.parent.get(import6.DOCUMENT))); }
    return this.__DomSanitizer_41;
  }
  get _Sanitizer_42():any {
    if ((this.__Sanitizer_42 == null)) { (this.__Sanitizer_42 = this._DomSanitizer_41); }
    return this.__Sanitizer_42;
  }
  get _HAMMER_GESTURE_CONFIG_43():import6.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_43 == null)) { (this.__HAMMER_GESTURE_CONFIG_43 = new import6.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_43;
  }
  get _EVENT_MANAGER_PLUGINS_44():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_44 == null)) { (this.__EVENT_MANAGER_PLUGINS_44 = [
      new import6.ɵDomEventsPlugin(this.parent.get(import6.DOCUMENT)),
      new import6.ɵKeyEventsPlugin(this.parent.get(import6.DOCUMENT)),
      new import6.ɵHammerGesturesPlugin(this.parent.get(import6.DOCUMENT),this._HAMMER_GESTURE_CONFIG_43)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_44;
  }
  get _EventManager_45():import6.EventManager {
    if ((this.__EventManager_45 == null)) { (this.__EventManager_45 = new import6.EventManager(this._EVENT_MANAGER_PLUGINS_44,this.parent.get(import0.NgZone))); }
    return this.__EventManager_45;
  }
  get _ɵDomSharedStylesHost_46():import6.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_46 == null)) { (this.__ɵDomSharedStylesHost_46 = new import6.ɵDomSharedStylesHost(this.parent.get(import6.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_46;
  }
  get _ɵDomRendererFactory2_47():import6.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_47 == null)) { (this.__ɵDomRendererFactory2_47 = new import6.ɵDomRendererFactory2(this._EventManager_45,this._ɵDomSharedStylesHost_46)); }
    return this.__ɵDomRendererFactory2_47;
  }
  get _RendererFactory2_48():any {
    if ((this.__RendererFactory2_48 == null)) { (this.__RendererFactory2_48 = this._ɵDomRendererFactory2_47); }
    return this.__RendererFactory2_48;
  }
  get _ɵSharedStylesHost_49():any {
    if ((this.__ɵSharedStylesHost_49 == null)) { (this.__ɵSharedStylesHost_49 = this._ɵDomSharedStylesHost_46); }
    return this.__ɵSharedStylesHost_49;
  }
  get _Testability_50():import0.Testability {
    if ((this.__Testability_50 == null)) { (this.__Testability_50 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_50;
  }
  get _Meta_51():import6.Meta {
    if ((this.__Meta_51 == null)) { (this.__Meta_51 = new import6.Meta(this.parent.get(import6.DOCUMENT))); }
    return this.__Meta_51;
  }
  get _Title_52():import6.Title {
    if ((this.__Title_52 == null)) { (this.__Title_52 = new import6.Title(this.parent.get(import6.DOCUMENT))); }
    return this.__Title_52;
  }
  get _ActivatedRoute_53():any {
    if ((this.__ActivatedRoute_53 == null)) { (this.__ActivatedRoute_53 = import5.ɵf(this._Router_23)); }
    return this.__ActivatedRoute_53;
  }
  get _NoPreloading_54():import5.NoPreloading {
    if ((this.__NoPreloading_54 == null)) { (this.__NoPreloading_54 = new import5.NoPreloading()); }
    return this.__NoPreloading_54;
  }
  get _PreloadingStrategy_55():any {
    if ((this.__PreloadingStrategy_55 == null)) { (this.__PreloadingStrategy_55 = this._NoPreloading_54); }
    return this.__PreloadingStrategy_55;
  }
  get _RouterPreloader_56():import5.RouterPreloader {
    if ((this.__RouterPreloader_56 == null)) { (this.__RouterPreloader_56 = new import5.RouterPreloader(this._Router_23,this._NgModuleFactoryLoader_21,this._Compiler_20,this,this._PreloadingStrategy_55)); }
    return this.__RouterPreloader_56;
  }
  get _PreloadAllModules_57():import5.PreloadAllModules {
    if ((this.__PreloadAllModules_57 == null)) { (this.__PreloadAllModules_57 = new import5.PreloadAllModules()); }
    return this.__PreloadAllModules_57;
  }
  get _ROUTER_INITIALIZER_58():any {
    if ((this.__ROUTER_INITIALIZER_58 == null)) { (this.__ROUTER_INITIALIZER_58 = import5.ɵi(this._ɵg_7)); }
    return this.__ROUTER_INITIALIZER_58;
  }
  get _APP_BOOTSTRAP_LISTENER_59():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_59 == null)) { (this.__APP_BOOTSTRAP_LISTENER_59 = [this._ROUTER_INITIALIZER_58]); }
    return this.__APP_BOOTSTRAP_LISTENER_59;
  }
  get _TwitterService_60():import9.TwitterService {
    if ((this.__TwitterService_60 == null)) { (this.__TwitterService_60 = new import9.TwitterService(this._Http_35)); }
    return this.__TwitterService_60;
  }
  get _PollService_61():import10.PollService {
    if ((this.__PollService_61 == null)) { (this.__PollService_61 = new import10.PollService(this._Http_35)); }
    return this.__PollService_61;
  }
  createInternal():import1.AppModule {
    this._ɵba_0 = new import2.ɵba();
    this._FormsModule_1 = new import2.FormsModule();
    this._ReactiveFormsModule_2 = new import2.ReactiveFormsModule();
    this._HttpModule_3 = new import3.HttpModule();
    this._CommonModule_4 = new import4.CommonModule();
    this._ErrorHandler_5 = import6.ɵa();
    this._NgProbeToken_6 = [import5.ɵb()];
    this._ɵg_7 = new import5.ɵg(this);
    this._APP_INITIALIZER_8 = [
      import0.ɵo,
      import6.ɵc(this.parent.get(import6.NgProbeToken,(null as any)),this._NgProbeToken_6),
      import5.ɵh(this._ɵg_7)
    ]
    ;
    this._ApplicationInitStatus_9 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_8);
    this._ɵf_10 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_5,this.componentFactoryResolver,this._ApplicationInitStatus_9);
    this._ApplicationRef_11 = this._ɵf_10;
    this._ApplicationModule_12 = new import0.ApplicationModule(this._ApplicationRef_11);
    this._BrowserModule_13 = new import6.BrowserModule(this.parent.get(import6.BrowserModule,(null as any)));
    this._ɵa_14 = import5.ɵd(this.parent.get(import5.Router,(null as any)));
    this._UrlSerializer_15 = new import5.DefaultUrlSerializer();
    this._RouterOutletMap_16 = new import5.RouterOutletMap();
    this._ROUTER_CONFIGURATION_17 = {};
    this._LocationStrategy_18 = import5.ɵc(this.parent.get(import4.PlatformLocation),this.parent.get(import4.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_17);
    this._Location_19 = new import4.Location(this._LocationStrategy_18);
    this._Compiler_20 = new import0.Compiler();
    this._NgModuleFactoryLoader_21 = new import0.SystemJsNgModuleLoader(this._Compiler_20,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_22 = [[
        {
          path: '',
          component: import14.NewpollsComponent
        }
        ,
        {
          path: 'newpolls',
          component: import14.NewpollsComponent
        }
        ,
        {
          path: 'mypolls',
          component: import15.MypollsComponent
        }

      ]
    ];
    this._Router_23 = import5.ɵe(this._ApplicationRef_11,this._UrlSerializer_15,this._RouterOutletMap_16,this._Location_19,this,this._NgModuleFactoryLoader_21,this._Compiler_20,this._ROUTES_22,this._ROUTER_CONFIGURATION_17,this.parent.get(import5.UrlHandlingStrategy,(null as any)),this.parent.get(import5.RouteReuseStrategy,(null as any)));
    this._RouterModule_24 = new import5.RouterModule(this._ɵa_14,this._Router_23);
    this._AppRoutingModule_25 = new import7.AppRoutingModule();
    this._ChartModule_26 = new import8.ChartModule();
    this._AppModule_27 = new import1.AppModule();
    return this._AppModule_27;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ɵba)) { return this._ɵba_0; }
    if ((token === import2.FormsModule)) { return this._FormsModule_1; }
    if ((token === import2.ReactiveFormsModule)) { return this._ReactiveFormsModule_2; }
    if ((token === import3.HttpModule)) { return this._HttpModule_3; }
    if ((token === import4.CommonModule)) { return this._CommonModule_4; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_5; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_6; }
    if ((token === import5.ɵg)) { return this._ɵg_7; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_8; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_9; }
    if ((token === import0.ɵf)) { return this._ɵf_10; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_11; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_12; }
    if ((token === import6.BrowserModule)) { return this._BrowserModule_13; }
    if ((token === import5.ɵa)) { return this._ɵa_14; }
    if ((token === import5.UrlSerializer)) { return this._UrlSerializer_15; }
    if ((token === import5.RouterOutletMap)) { return this._RouterOutletMap_16; }
    if ((token === import5.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_17; }
    if ((token === import4.LocationStrategy)) { return this._LocationStrategy_18; }
    if ((token === import4.Location)) { return this._Location_19; }
    if ((token === import0.Compiler)) { return this._Compiler_20; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_21; }
    if ((token === import5.ROUTES)) { return this._ROUTES_22; }
    if ((token === import5.Router)) { return this._Router_23; }
    if ((token === import5.RouterModule)) { return this._RouterModule_24; }
    if ((token === import7.AppRoutingModule)) { return this._AppRoutingModule_25; }
    if ((token === import8.ChartModule)) { return this._ChartModule_26; }
    if ((token === import1.AppModule)) { return this._AppModule_27; }
    if ((token === import2.ɵi)) { return this._ɵi_28; }
    if ((token === import2.FormBuilder)) { return this._FormBuilder_29; }
    if ((token === import3.BrowserXhr)) { return this._BrowserXhr_30; }
    if ((token === import3.ResponseOptions)) { return this._ResponseOptions_31; }
    if ((token === import3.XSRFStrategy)) { return this._XSRFStrategy_32; }
    if ((token === import3.XHRBackend)) { return this._XHRBackend_33; }
    if ((token === import3.RequestOptions)) { return this._RequestOptions_34; }
    if ((token === import3.Http)) { return this._Http_35; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_36; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_37; }
    if ((token === import0.APP_ID)) { return this._APP_ID_38; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_39; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_40; }
    if ((token === import6.DomSanitizer)) { return this._DomSanitizer_41; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_42; }
    if ((token === import6.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_43; }
    if ((token === import6.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_44; }
    if ((token === import6.EventManager)) { return this._EventManager_45; }
    if ((token === import6.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_46; }
    if ((token === import6.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_47; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_48; }
    if ((token === import6.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_49; }
    if ((token === import0.Testability)) { return this._Testability_50; }
    if ((token === import6.Meta)) { return this._Meta_51; }
    if ((token === import6.Title)) { return this._Title_52; }
    if ((token === import5.ActivatedRoute)) { return this._ActivatedRoute_53; }
    if ((token === import5.NoPreloading)) { return this._NoPreloading_54; }
    if ((token === import5.PreloadingStrategy)) { return this._PreloadingStrategy_55; }
    if ((token === import5.RouterPreloader)) { return this._RouterPreloader_56; }
    if ((token === import5.PreloadAllModules)) { return this._PreloadAllModules_57; }
    if ((token === import5.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_58; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_59; }
    if ((token === import9.TwitterService)) { return this._TwitterService_60; }
    if ((token === import10.PollService)) { return this._PollService_61; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_10.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_46 && this._ɵDomSharedStylesHost_46.ngOnDestroy());
    (this.__RouterPreloader_56 && this._RouterPreloader_56.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvbmd0aG8vRG9jdW1lbnRzL0phdmFTY3JpcHQvVm90aW5nX2FwcC9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
